name: Manual Nightly release

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Specify the branch you want
          ref: development
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package


      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: false
          title: "Nightly Build"
          files: |
            /home/runner/work/microbot/microbot/runelite-client/target/*.jar

      - name: Upload Jar
        uses: "bacongobbler/azure-blob-storage-upload@main"
        with:
          source_dir: runelite-client/target/jars
          container_name: microbot
          connection_string: ${{ secrets.blobConnectionString }}
          extra_args: '--pattern *.jar --destination-path nightly'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
